# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Hamming Distance
#'
#' \code{hamming} computes the hamming distance between two equal length strings. The hamming distance
#' is the number of different characters between strings. Is called by \code{\link{get_mapped_barcode_indices}}.
#'
#' @param str1 The first string, should be equal length to \code{str2}
#' @param str2 The second string, should be equal length to \code{str1}
#' @return Returns the hamming distance, a scalar integer
hamming <- function(str1, str2) {
    .Call(`_SequenceMapper_hamming`, str1, str2)
}

